const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000, ROOT=__dirname, DB=process.env.DB_PATH?path.resolve(process.env.DB_PATH):path.join(ROOT,'data','db.json');
// Loads local secrets if a .env file exists. On production, use host environment variables instead.
const envFile=path.join(ROOT,'.env');if(fs.existsSync(envFile))for(const line of fs.readFileSync(envFile,'utf8').split(/\r?\n/)){let m=line.match(/^([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].trim()}
const GOOGLE_CLIENT_ID=process.env.GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=process.env.GOOGLE_CLIENT_SECRET,GOOGLE_REDIRECT_URI=process.env.GOOGLE_REDIRECT_URI,API_FOOTBALL_KEY=process.env.API_FOOTBALL_KEY;
function read(){let x=JSON.parse(fs.readFileSync(DB,'utf8'));x.investments??=[];x.accounts??=[];x.budgets??=[];x.projects??=[];x.timeEntries??=[];x.habits??=[];x.habitLogs??=[];x.subscriptions??=[];x.debts??=[];x.footballTeams??=[];x.matches??=[];x.news??=[];x.movies??=[];x.timers??=[];return x}function write(x){fs.writeFileSync(DB,JSON.stringify(x,null,2))}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))}
function body(req){return new Promise((ok,no)=>{let d='';req.on('data',x=>d+=x);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}})})}
function hash(p,s){return crypto.pbkdf2Sync(p,s,130000,32,'sha256').toString('hex')}
function id(){return crypto.randomUUID()}function cookie(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=')))}
function me(req,db){let sid=cookie(req).sid;let s=db.sessions.find(x=>x.id===sid);return s&&db.users.find(x=>x.id===s.userId)}
class AuthError extends Error{}
function auth(req,res,db){let u=me(req,db);if(!u){json(res,401,{error:'ابتدا وارد حساب شوید.'});throw new AuthError()}return u}
function today(){return new Date().toISOString().slice(0,10)}
function enNum(v){return String(v).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d))}
function parseLifeText(text){let t=enNum(text),actions=[],m=t.match(/(?:خرید(?:م)?|خرج کردم|هزینه)[^\d]{0,25}(\d[\d,]*)/);if(m){let a=Number(m[1].replace(/,/g,''));actions.push({type:'transaction',amount:a,title:'هزینه ثبت‌شده از متن',category:/نان|رستوران|شام|غذا|کافه/.test(t)?'خوراک':'متفرقه'})}let w=t.match(/(\d+(?:\.\d+)?)\s*(?:ساعت|ساعتِ?)\s*(?:روی|کار)/);if(w)actions.push({type:'time',minutes:Math.round(Number(w[1])*60),title:'کار ثبت‌شده از متن'});let mood=t.match(/(?:حالم|مود)[^\d]{0,12}(\d{1,2})/);if(mood)actions.push({type:'mood',value:Math.min(10,Number(mood[1]))});let sleep=t.match(/(\d+(?:\.\d+)?)\s*ساعت\s*(?:خواب|خوابیدم)/);if(sleep)actions.push({type:'sleep',value:sleep[1]+' ساعت'});return actions}
let dbLock=Promise.resolve();
async function handleRequest(req,res){try{let u=new URL(req.url,'http://x'), p=u.pathname;
 if(p==='/api/auth/signup'&&req.method==='POST'){let d=await body(req),db=read();if(!d.name||!d.email||!d.password||d.password.length<6)return json(res,400,{error:'نام، ایمیل و رمز حداقل ۶ حرفی لازم است.'});if(db.users.some(x=>x.email===d.email.toLowerCase()))return json(res,409,{error:'این ایمیل قبلاً ثبت شده است.'});let salt=crypto.randomBytes(16).toString('hex'),user={id:id(),name:d.name.trim(),email:d.email.toLowerCase(),salt,password:hash(d.password,salt),createdAt:Date.now()};db.users.push(user);let sid=id();db.sessions.push({id:sid,userId:user.id});write(db);res.writeHead(201,{'Content-Type':'application/json','Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000`});return res.end(JSON.stringify({user:{name:user.name,email:user.email}}))}
 if(p==='/api/auth/login'&&req.method==='POST'){let d=await body(req),db=read(),user=db.users.find(x=>x.email===String(d.email).toLowerCase()),candidate=hash(d.password||'',(user&&user.salt)||'0000000000000000000000000000000'),valid=user&&user.password&&crypto.timingSafeEqual(Buffer.from(candidate),Buffer.from(user.password));if(!valid)return json(res,401,{error:'ایمیل یا رمز عبور صحیح نیست.'});let sid=id();db.sessions.push({id:sid,userId:user.id});write(db);res.writeHead(200,{'Content-Type':'application/json','Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000`});return res.end(JSON.stringify({user:{name:user.name,email:user.email}}))}
 if(p==='/api/auth/google'&&req.method==='GET'){if(!GOOGLE_CLIENT_ID||!GOOGLE_CLIENT_SECRET||!GOOGLE_REDIRECT_URI)return json(res,503,{error:'ورود گوگل هنوز در تنظیمات سرور فعال نشده است.'});let state=crypto.randomBytes(24).toString('hex'),q=new URLSearchParams({client_id:GOOGLE_CLIENT_ID,redirect_uri:GOOGLE_REDIRECT_URI,response_type:'code',scope:'openid email profile',state,prompt:'select_account'});res.writeHead(302,{'Location':'https://accounts.google.com/o/oauth2/v2/auth?'+q,'Set-Cookie':`google_state=${state}; HttpOnly; SameSite=Lax; Path=/; Max-Age=600`});return res.end()}
 if(p==='/api/auth/google/callback'&&req.method==='GET'){let db=read(),code=u.searchParams.get('code'),state=u.searchParams.get('state');if(!code||!state||cookie(req).google_state!==state)return json(res,400,{error:'تأیید امنیتی ورود گوگل ناموفق بود. دوباره تلاش کن.'});if(!GOOGLE_CLIENT_ID||!GOOGLE_CLIENT_SECRET||!GOOGLE_REDIRECT_URI)return json(res,503,{error:'تنظیمات گوگل کامل نیست.'});let token=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:GOOGLE_CLIENT_ID,client_secret:GOOGLE_CLIENT_SECRET,redirect_uri:GOOGLE_REDIRECT_URI,grant_type:'authorization_code'})}).then(r=>r.json());if(!token.access_token)return json(res,401,{error:'دریافت مجوز گوگل ناموفق بود.'});let profile=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:'Bearer '+token.access_token}}).then(r=>r.json());if(!profile.email||!profile.sub)return json(res,401,{error:'اطلاعات حساب گوگل کامل نیست.'});let user=db.users.find(x=>x.googleId===profile.sub)||db.users.find(x=>x.email===profile.email.toLowerCase());if(!user){user={id:id(),name:profile.name||profile.email.split('@')[0],email:profile.email.toLowerCase(),googleId:profile.sub,createdAt:Date.now()};db.users.push(user)}else if(!user.googleId)user.googleId=profile.sub;let sid=id();db.sessions.push({id:sid,userId:user.id});write(db);res.writeHead(302,{'Location':'/','Set-Cookie':[`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000`,'google_state=; HttpOnly; Path=/; Max-Age=0']});return res.end()}
 if(p==='/api/auth/logout'&&req.method==='POST'){let db=read(),sid=cookie(req).sid;db.sessions=db.sessions.filter(x=>x.id!==sid);write(db);res.writeHead(200,{'Set-Cookie':'sid=; HttpOnly; Path=/; Max-Age=0'});return res.end('{}')}
 if(p==='/api/me'){let db=read(),user=me(req,db);return json(res,200,{user:user&&{name:user.name,email:user.email}})}
 if(p==='/api/export'){let db=read(),user=auth(req,res,db);let out={exportedAt:new Date().toISOString(),version:'0.1',user:{name:user.name,email:user.email},transactions:db.transactions.filter(x=>x.userId===user.id),tasks:db.tasks.filter(x=>x.userId===user.id),inbox:db.inbox.filter(x=>x.userId===user.id),daily:db.daily.filter(x=>x.userId===user.id),investments:db.investments.filter(x=>x.userId===user.id),accounts:db.accounts.filter(x=>x.userId===user.id),budgets:db.budgets.filter(x=>x.userId===user.id),projects:db.projects.filter(x=>x.userId===user.id),timeEntries:db.timeEntries.filter(x=>x.userId===user.id),habits:db.habits.filter(x=>x.userId===user.id),habitLogs:db.habitLogs.filter(x=>db.habits.some(h=>h.id===x.habitId&&h.userId===user.id)),subscriptions:db.subscriptions.filter(x=>x.userId===user.id)};res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Content-Disposition':'attachment; filename="haste-backup.json"'});return res.end(JSON.stringify(out,null,2))}
 if(p==='/api/dashboard'){let db=read(),user=auth(req,res,db);let date=u.searchParams.get('date')||today();return json(res,200,{date,tasks:db.tasks.filter(x=>x.userId===user.id&&x.date===date),transactions:db.transactions.filter(x=>x.userId===user.id&&x.date===date).sort((a,b)=>b.createdAt-a.createdAt),inbox:db.inbox.filter(x=>x.userId===user.id&&!x.archived).sort((a,b)=>b.createdAt-a.createdAt),daily:db.daily.find(x=>x.userId===user.id&&x.date===date)||null})}
 if(p==='/api/days'){let db=read(),user=auth(req,res,db);let from=u.searchParams.get('from')||today(),to=u.searchParams.get('to')||today();let dates=new Set([...db.tasks.filter(x=>x.userId===user.id&&x.date>=from&&x.date<=to).map(x=>x.date),...db.transactions.filter(x=>x.userId===user.id&&x.date>=from&&x.date<=to).map(x=>x.date),...db.daily.filter(x=>x.userId===user.id&&x.date>=from&&x.date<=to).map(x=>x.date)]);return json(res,200,{dates:[...dates]})}
 if(p==='/api/transactions'&&req.method==='GET'){let db=read(),user=auth(req,res,db);let month=u.searchParams.get('month')||today().slice(0,7);return json(res,200,{items:db.transactions.filter(x=>x.userId===user.id&&x.date.startsWith(month)).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt)})}
 if(p.startsWith('/api/transactions/')&&(req.method==='PATCH'||req.method==='DELETE')){let db=read(),user=auth(req,res,db);let ix=db.transactions.findIndex(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(ix<0)return json(res,404,{error:'تراکنش پیدا نشد.'});if(req.method==='DELETE'){db.transactions.splice(ix,1);write(db);return json(res,200,{ok:true})}let d=await body(req),r=db.transactions[ix];for(const k of ['title','amount','category','kind','account','date'])if(d[k]!==undefined)r[k]=k==='amount'?Number(d[k]):d[k];write(db);return json(res,200,r)}
 if(p==='/api/transactions'&&req.method==='POST'){let db=read(),user=auth(req,res,db);let d=await body(req);if(!d.title||!Number(d.amount))return json(res,400,{error:'شرح و مبلغ الزامی است.'});let r={id:id(),userId:user.id,title:d.title.trim(),amount:Number(d.amount),category:d.category||'متفرقه',kind:d.kind||'expense',account:d.account||'بدون حساب',date:d.date||today(),createdAt:Date.now()};db.transactions.push(r);write(db);return json(res,201,r)}
 if(p==='/api/tasks'&&req.method==='POST'){let db=read(),user=auth(req,res,db);let d=await body(req);if(!d.title)return json(res,400,{error:'عنوان کار لازم است.'});let r={id:id(),userId:user.id,title:d.title.trim(),date:d.date||today(),done:false,priority:d.priority||'medium',deadline:d.deadline||null,projectId:d.projectId||null,parentTaskId:d.parentTaskId||null,recurrence:d.recurrence||null,createdAt:Date.now()};db.tasks.push(r);write(db);return json(res,201,r)}
 if(p.startsWith('/api/tasks/')&&req.method==='DELETE'){let db=read(),user=auth(req,res,db);let ix=db.tasks.findIndex(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(ix<0)return json(res,404,{error:'تسک پیدا نشد.'});let dead=new Set([db.tasks[ix].id]),grew=true;while(grew){grew=false;for(const t of db.tasks)if(t.parentTaskId&&dead.has(t.parentTaskId)&&!dead.has(t.id)){dead.add(t.id);grew=true}}db.tasks=db.tasks.filter(x=>!dead.has(x.id));write(db);return json(res,200,{ok:true})}
 if(p.startsWith('/api/tasks/')&&req.method==='PATCH'){let db=read(),user=auth(req,res,db);let r=db.tasks.find(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(!r)return json(res,404,{error:'پیدا نشد'});let d=await body(req),wasDone=r.done;for(const k of ['title','done','priority','deadline','projectId','parentTaskId','recurrence','date'])if(d[k]!==undefined)r[k]=d[k];if(r.done&&!wasDone&&r.recurrence){let next=new Date(r.date+'T12:00:00');if(r.recurrence==='weekly')next.setDate(next.getDate()+7);else if(r.recurrence==='monthly')next.setMonth(next.getMonth()+1);else next.setDate(next.getDate()+1);db.tasks.push({id:id(),userId:user.id,title:r.title,date:next.toISOString().slice(0,10),done:false,priority:r.priority,deadline:null,projectId:r.projectId,parentTaskId:null,recurrence:r.recurrence,createdAt:Date.now()})}write(db);return json(res,200,r)}
 if(p==='/api/inbox'&&req.method==='POST'){let db=read(),user=auth(req,res,db);let d=await body(req);if(!d.text)return json(res,400,{error:'متن لازم است.'});let r={id:id(),userId:user.id,text:d.text.trim(),archived:false,createdAt:Date.now()};db.inbox.push(r);write(db);return json(res,201,r)}
 if(p.startsWith('/api/inbox/')&&p.endsWith('/convert')&&req.method==='POST'){let db=read(),user=auth(req,res,db);let item=db.inbox.find(x=>x.id===p.split('/')[3]&&x.userId===user.id);if(!item)return json(res,404,{error:'آیتم پیدا نشد.'});let d=await body(req),date=d.date||today();if(d.type==='task')db.tasks.push({id:id(),userId:user.id,title:item.text,date,done:false,createdAt:Date.now()});else if(d.type==='note'){let daily=db.daily.find(x=>x.userId===user.id&&x.date===date);if(daily)daily.note=(daily.note?daily.note+'\n':'')+item.text;else db.daily.push({id:id(),userId:user.id,date,mood:7,energy:7,sleep:'',note:item.text})}else return json(res,400,{error:'نوع تبدیل معتبر نیست.'});item.archived=true;write(db);return json(res,200,{ok:true})}
 if(p==='/api/search'){let db=read(),user=auth(req,res,db);let q=(u.searchParams.get('q')||'').trim().toLowerCase();if(!q)return json(res,200,{items:[]});let out=[];for(const x of db.tasks.filter(x=>x.userId===user.id&&x.title.toLowerCase().includes(q)))out.push({type:'تسک',text:x.title,date:x.date});for(const x of db.transactions.filter(x=>x.userId===user.id&&x.title.toLowerCase().includes(q)))out.push({type:'تراکنش',text:x.title+' · '+x.amount.toLocaleString('fa-IR')+' تومان',date:x.date});for(const x of db.inbox.filter(x=>x.userId===user.id&&x.text.toLowerCase().includes(q)))out.push({type:'Inbox',text:x.text,date:''});for(const x of db.daily.filter(x=>x.userId===user.id&&(x.note||'').toLowerCase().includes(q)))out.push({type:'یادداشت',text:x.note,date:x.date});return json(res,200,{items:out.slice(0,30)})}
 if(p==='/api/daily'&&req.method==='PUT'){let db=read(),user=auth(req,res,db),d=await body(req);let r=db.daily.find(x=>x.userId===user.id&&x.date===(d.date||today()));if(r)Object.assign(r,d);else{r={id:id(),userId:user.id,date:d.date||today(),mood:7,energy:7,sleep:'',note:'',bestMoment:'',gratitude:'',tomorrowPlan:'',...d};db.daily.push(r)}write(db);return json(res,200,r)}
 if(p==='/api/finance'){let db=read(),user=auth(req,res,db);let month=u.searchParams.get('month')||today().slice(0,7),all=db.transactions.filter(x=>x.userId===user.id&&x.date.startsWith(month)),expense=all.filter(x=>x.kind!=='income').reduce((n,x)=>n+x.amount,0),income=all.filter(x=>x.kind==='income').reduce((n,x)=>n+x.amount,0),categories={};all.filter(x=>x.kind!=='income').forEach(x=>categories[x.category]=(categories[x.category]||0)+x.amount);return json(res,200,{month,income,expense,balance:income-expense,categories})}
 if(p==='/api/movies'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let status=u.searchParams.get('status');return json(res,200,{items:db.movies.filter(x=>x.userId===user.id&&(!status||x.status===status)).sort((a,b)=>b.createdAt-a.createdAt)})}if(req.method==='POST'){let d=await body(req);if(!d.title)return json(res,400,{error:'عنوان لازم است.'});let r={id:id(),userId:user.id,title:d.title.trim(),type:d.type||'movie',status:d.status||'watchlist',rating:d.rating||null,progress:d.progress||'',date:d.date||today(),note:d.note||'',tags:d.tags||'',createdAt:Date.now()};db.movies.push(r);write(db);return json(res,201,r)}}
 if(p.startsWith('/api/movies/')&&(req.method==='PATCH'||req.method==='DELETE')){let db=read(),user=auth(req,res,db);let ix=db.movies.findIndex(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(ix<0)return json(res,404,{error:'آیتم پیدا نشد.'});if(req.method==='DELETE'){db.movies.splice(ix,1);write(db);return json(res,200,{ok:true})}let d=await body(req),r=db.movies[ix];for(const k of ['status','rating','progress','note','tags'])if(d[k]!==undefined)r[k]=d[k];write(db);return json(res,200,r)}
 if(p==='/api/news'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let date=u.searchParams.get('date'),items=db.news.filter(x=>x.userId===user.id&&(!date||x.date===date)).sort((a,b)=>b.createdAt-a.createdAt);return json(res,200,{items})}if(req.method==='POST'){let d=await body(req);if(!d.title)return json(res,400,{error:'عنوان خبر لازم است.'});let r={id:id(),userId:user.id,title:d.title.trim(),source:d.source||'',category:d.category||'عمومی',url:d.url||'',summary:d.summary||'',date:d.date||today(),saved:!!d.saved,createdAt:Date.now()};db.news.push(r);write(db);return json(res,201,r)}}
 if(p.startsWith('/api/news/')&&req.method==='PATCH'){let db=read(),user=auth(req,res,db);let r=db.news.find(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(!r)return json(res,404,{error:'خبر پیدا نشد.'});let d=await body(req);for(const k of ['saved','title','summary','category'])if(d[k]!==undefined)r[k]=d[k];write(db);return json(res,200,r)}
 if(p==='/api/football/remote/fixtures'){let db=read(),user=auth(req,res,db);if(!API_FOOTBALL_KEY)return json(res,503,{error:'کلید API-Football هنوز در تنظیمات سرور وارد نشده است.'});let date=u.searchParams.get('date')||today(),league=u.searchParams.get('league'),qs=new URLSearchParams({date});if(league)qs.set('league',league);let r=await fetch('https://v3.football.api-sports.io/fixtures?'+qs,{headers:{'x-apisports-key':API_FOOTBALL_KEY}}),data=await r.json();if(!r.ok)return json(res,r.status,{error:data.message||'خطا در دریافت بازی‌ها'});return json(res,200,{items:(data.response||[]).map(x=>({fixtureId:x.fixture.id,home:x.teams.home.name,away:x.teams.away.name,league:x.league.name,date:x.fixture.date,status:x.fixture.status.short,score:(x.goals.home??'-')+' - '+(x.goals.away??'-')}))})}
 if(p==='/api/football/remote/odds'){let db=read(),user=auth(req,res,db);if(!API_FOOTBALL_KEY)return json(res,503,{error:'کلید API-Football هنوز در تنظیمات سرور وارد نشده است.'});let fixture=u.searchParams.get('fixture');if(!fixture)return json(res,400,{error:'شناسه بازی لازم است.'});let r=await fetch('https://v3.football.api-sports.io/odds?fixture='+encodeURIComponent(fixture)+'&bookmaker=11',{headers:{'x-apisports-key':API_FOOTBALL_KEY}}),data=await r.json();if(!r.ok)return json(res,r.status,{error:data.message||'خطا در دریافت ضرایب'});let item=(data.response||[])[0],book=item?.bookmakers?.find(x=>x.name==='1xBet')||item?.bookmakers?.[0];return json(res,200,{bookmaker:book?.name||'1xBet',bets:book?.bets||[]})}
 if(p==='/api/football/teams'){let db=read(),user=auth(req,res,db);if(req.method==='GET')return json(res,200,{items:db.footballTeams.filter(x=>x.userId===user.id)});if(req.method==='POST'){let d=await body(req);if(!d.name)return json(res,400,{error:'نام تیم لازم است.'});let r={id:id(),userId:user.id,name:d.name.trim(),league:d.league||'',createdAt:Date.now()};db.footballTeams.push(r);write(db);return json(res,201,r)}}
 if(p==='/api/football/matches'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let from=u.searchParams.get('from')||today(),to=u.searchParams.get('to')||'9999-12-31';return json(res,200,{items:db.matches.filter(x=>x.userId===user.id&&x.date>=from&&x.date<=to).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))})}if(req.method==='POST'){let d=await body(req);if(!d.home||!d.away||!d.date)return json(res,400,{error:'دو تیم و تاریخ بازی لازم است.'});let r={id:id(),userId:user.id,home:d.home.trim(),away:d.away.trim(),league:d.league||'',date:d.date,time:d.time||'',status:d.status||'upcoming',score:d.score||'',rating:d.rating||null,note:d.note||'',prediction:d.prediction||'',createdAt:Date.now()};db.matches.push(r);write(db);return json(res,201,r)}}
 if(p.startsWith('/api/football/matches/')&&req.method==='PATCH'){let db=read(),user=auth(req,res,db);let r=db.matches.find(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(!r)return json(res,404,{error:'بازی پیدا نشد.'});let d=await body(req);for(const k of ['status','score','rating','note','prediction','date','time','league'])if(d[k]!==undefined)r[k]=d[k];write(db);return json(res,200,r)}
 if(p==='/api/debts'){let db=read(),user=auth(req,res,db);if(req.method==='GET')return json(res,200,{items:db.debts.filter(x=>x.userId===user.id&&!x.settled).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'))});if(req.method==='POST'){let d=await body(req);if(!d.person||!Number(d.amount))return json(res,400,{error:'نام شخص و مبلغ لازم است.'});let r={id:id(),userId:user.id,person:d.person.trim(),amount:Number(d.amount),type:d.type||'receivable',dueDate:d.dueDate||null,note:d.note||'',settled:false,createdAt:Date.now()};db.debts.push(r);write(db);return json(res,201,r)}}
 if(p.startsWith('/api/debts/')&&p.endsWith('/settle')&&req.method==='POST'){let db=read(),user=auth(req,res,db);let r=db.debts.find(x=>x.id===p.split('/')[3]&&x.userId===user.id);if(!r)return json(res,404,{error:'رکورد پیدا نشد.'});r.settled=true;write(db);return json(res,200,r)}
 if(p.startsWith('/api/subscriptions/')&&p.endsWith('/pay')&&req.method==='POST'){let db=read(),user=auth(req,res,db);let r=db.subscriptions.find(x=>x.id===p.split('/')[3]&&x.userId===user.id);if(!r)return json(res,404,{error:'اشتراک پیدا نشد.'});let d=new Date(r.nextDate+'T12:00:00');if(r.cycle==='weekly')d.setDate(d.getDate()+7);else if(r.cycle==='yearly')d.setFullYear(d.getFullYear()+1);else d.setMonth(d.getMonth()+1);db.transactions.push({id:id(),userId:user.id,title:r.name,amount:r.amount,category:'اشتراک‌ها',kind:'expense',account:r.account||'بدون حساب',date:r.nextDate,createdAt:Date.now()});r.nextDate=d.toISOString().slice(0,10);write(db);return json(res,200,r)}
 if(p==='/api/subscriptions'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let items=db.subscriptions.filter(x=>x.userId===user.id&&!x.archived).sort((a,b)=>a.nextDate.localeCompare(b.nextDate));return json(res,200,{items})}if(req.method==='POST'){let d=await body(req);if(!d.name||!Number(d.amount)||!d.nextDate)return json(res,400,{error:'نام، مبلغ و تاریخ تمدید لازم است.'});let r={id:id(),userId:user.id,name:d.name.trim(),amount:Number(d.amount),cycle:d.cycle||'monthly',nextDate:d.nextDate,account:d.account||'بدون حساب',archived:false,createdAt:Date.now()};db.subscriptions.push(r);write(db);return json(res,201,r)}}
 if(p==='/api/habits'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let date=u.searchParams.get('date')||today(),items=db.habits.filter(x=>x.userId===user.id&&!x.archived).map(x=>{let done=db.habitLogs.some(l=>l.habitId===x.id&&l.date===date&&l.done),d=new Date(date+'T12:00:00'),streak=0;while(db.habitLogs.some(l=>l.habitId===x.id&&l.date===d.toISOString().slice(0,10)&&l.done)){streak++;d.setDate(d.getDate()-1)}return {...x,done,streak}});return json(res,200,{items})}if(req.method==='POST'){let d=await body(req);if(!d.name)return json(res,400,{error:'نام عادت لازم است.'});let r={id:id(),userId:user.id,name:d.name.trim(),icon:d.icon||'✓',archived:false,createdAt:Date.now()};db.habits.push(r);write(db);return json(res,201,r)}}
 if(p.startsWith('/api/habits/')&&p.endsWith('/toggle')&&req.method==='POST'){let db=read(),user=auth(req,res,db);let habitId=p.split('/')[3],h=db.habits.find(x=>x.id===habitId&&x.userId===user.id);if(!h)return json(res,404,{error:'عادت پیدا نشد.'});let d=await body(req),date=d.date||today(),log=db.habitLogs.find(x=>x.habitId===habitId&&x.date===date);if(log)log.done=!log.done;else{log={id:id(),habitId,date,done:true};db.habitLogs.push(log)}write(db);return json(res,200,log)}
 if(p.startsWith('/api/habits/')&&!p.endsWith('/toggle')&&(req.method==='PATCH'||req.method==='DELETE')){let db=read(),user=auth(req,res,db),habitId=p.split('/').pop(),h=db.habits.find(x=>x.id===habitId&&x.userId===user.id);if(!h)return json(res,404,{error:'عادت پیدا نشد.'});if(req.method==='DELETE'){db.habits=db.habits.filter(x=>x.id!==habitId);db.habitLogs=db.habitLogs.filter(x=>x.habitId!==habitId);write(db);return json(res,200,{ok:true})}let d=await body(req);for(const k of ['name','icon','archived'])if(d[k]!==undefined)h[k]=d[k];write(db);return json(res,200,h)}
 if(p==='/api/ai/process'&&req.method==='POST'){let db=read(),user=auth(req,res,db);let d=await body(req),date=d.date||today(),actions=parseLifeText(d.text||''),done=[];let daily=db.daily.find(x=>x.userId===user.id&&x.date===date);for(const a of actions){if(a.type==='transaction'){db.transactions.push({id:id(),userId:user.id,title:a.title,amount:a.amount,category:a.category,kind:'expense',account:'بدون حساب',date,createdAt:Date.now()});done.push('هزینه '+a.amount.toLocaleString('fa-IR')+' تومان')}if(a.type==='time'){db.timeEntries.push({id:id(),userId:user.id,title:a.title,projectId:null,minutes:a.minutes,date,createdAt:Date.now()});done.push('کار '+a.minutes+' دقیقه')}if(a.type==='mood'||a.type==='sleep'){if(!daily){daily={id:id(),userId:user.id,date,mood:7,energy:7,sleep:'',note:''};db.daily.push(daily)}if(a.type==='mood'){daily.mood=a.value;done.push('مود '+a.value)}else{daily.sleep=a.value;done.push('خواب '+a.value)}}}write(db);return json(res,200,{actions,done})}
 if(p==='/api/insights'){let db=read(),user=auth(req,res,db);let month=u.searchParams.get('month')||today().slice(0,7),t=db.transactions.filter(x=>x.userId===user.id&&x.date.startsWith(month)),expense=t.filter(x=>x.kind!=='income'),by={};expense.forEach(x=>by[x.category]=(by[x.category]||0)+x.amount);let top=Object.entries(by).sort((a,b)=>b[1]-a[1])[0],time=db.timeEntries.filter(x=>x.userId===user.id&&x.date.startsWith(month)).reduce((n,x)=>n+x.minutes,0),daily=db.daily.filter(x=>x.userId===user.id&&x.date.startsWith(month)),moods=daily.filter(x=>x.mood).map(x=>x.mood),avg=moods.length?moods.reduce((a,b)=>a+b,0)/moods.length:null,h=db.habits.filter(x=>x.userId===user.id&&!x.archived),logs=db.habitLogs,ins=[];if(top)ins.push({icon:'💸',text:`بیشترین هزینهٔ این ماه «${top[0]}» بوده: ${top[1].toLocaleString('fa-IR')} تومان.`});if(time)ins.push({icon:'⏱',text:`این ماه ${Math.floor(time/60).toLocaleString('fa-IR')} ساعت و ${(time%60).toLocaleString('fa-IR')} دقیقه زمان کار ثبت کرده‌ای.`});if(avg!==null)ins.push({icon:avg>=7?'🙂':'🧠',text:`میانگین حال ثبت‌شده‌ات در این ماه ${avg.toFixed(1)} از ۱۰ است.`});let best=h.map(x=>{let n=0;for(const l of logs)if(l.habitId===x.id&&l.done)n++;return [x,n]}).sort((a,b)=>b[1]-a[1])[0];if(best&&best[1])ins.push({icon:'🔥',text:`پایدارترین عادت ثبت‌شده: ${best[0].name} با ${best[1].toLocaleString('fa-IR')} روز انجام.`});let overdue=db.subscriptions.filter(x=>x.userId===user.id&&!x.archived&&x.nextDate<today());if(overdue.length)ins.push({icon:'⚠️',text:`${overdue.length.toLocaleString('fa-IR')} اشتراک سررسید گذشته داری؛ بخش تمدیدها را بررسی کن.`});return json(res,200,{items:ins})}
 if(p==='/api/reports'){let db=read(),user=auth(req,res,db);let month=u.searchParams.get('month')||today().slice(0,7),days=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate(),items=[];for(let n=1;n<=days;n++){let date=month+'-'+String(n).padStart(2,'0'),trans=db.transactions.filter(x=>x.userId===user.id&&x.date===date),time=db.timeEntries.filter(x=>x.userId===user.id&&x.date===date),daily=db.daily.find(x=>x.userId===user.id&&x.date===date);items.push({date,expense:trans.filter(x=>x.kind!=='income').reduce((a,x)=>a+x.amount,0),income:trans.filter(x=>x.kind==='income').reduce((a,x)=>a+x.amount,0),minutes:time.reduce((a,x)=>a+x.minutes,0),mood:daily?.mood||null,energy:daily?.energy||null,sleep:daily?.sleep||''})}return json(res,200,{month,days:items})}
 if(p==='/api/projects'){let db=read(),user=auth(req,res,db);if(req.method==='GET')return json(res,200,{items:db.projects.filter(x=>x.userId===user.id)});if(req.method==='POST'){let d=await body(req);if(!d.name)return json(res,400,{error:'نام پروژه لازم است.'});let r={id:id(),userId:user.id,name:d.name.trim(),color:d.color||'#5ca4ff',createdAt:Date.now()};db.projects.push(r);write(db);return json(res,201,r)}}
 if(p.startsWith('/api/projects/')&&req.method==='DELETE'){let db=read(),user=auth(req,res,db);let ix=db.projects.findIndex(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(ix<0)return json(res,404,{error:'پروژه پیدا نشد.'});db.projects.splice(ix,1);write(db);return json(res,200,{ok:true})}
 if(p.startsWith('/api/time/')&&(req.method==='PATCH'||req.method==='DELETE')){let db=read(),user=auth(req,res,db);let ix=db.timeEntries.findIndex(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(ix<0)return json(res,404,{error:'ثبت زمان پیدا نشد.'});if(req.method==='DELETE'){db.timeEntries.splice(ix,1);write(db);return json(res,200,{ok:true})}let d=await body(req),r=db.timeEntries[ix];for(const k of ['title','minutes','projectId','date'])if(d[k]!==undefined)r[k]=k==='minutes'?Number(d[k]):d[k];write(db);return json(res,200,r)}
 if(p==='/api/timer'&&req.method==='GET'){let db=read(),user=auth(req,res,db),t=db.timers.find(x=>x.userId===user.id);return json(res,200,{timer:t||null})}
 if(p==='/api/timer/start'&&req.method==='POST'){let db=read(),user=auth(req,res,db),existing=db.timers.find(x=>x.userId===user.id);if(existing)return json(res,409,{error:'یک تایمر در حال اجراست.',timer:existing});let d=await body(req);if(!d.title)return json(res,400,{error:'عنوان کار لازم است.'});let t={id:id(),userId:user.id,title:d.title.trim(),projectId:d.projectId||null,startedAt:Date.now(),deadlineAt:d.deadlineAt||null};db.timers.push(t);write(db);return json(res,201,t)}
 if(p==='/api/timer/stop'&&req.method==='POST'){let db=read(),user=auth(req,res,db),t=db.timers.find(x=>x.userId===user.id);if(!t)return json(res,404,{error:'تایمری در حال اجرا نیست.'});let d=await body(req);db.timers=db.timers.filter(x=>x.id!==t.id);let minutes=Math.max(1,Math.round((Date.now()-t.startedAt)/60000)),r={id:id(),userId:user.id,title:t.title,projectId:t.projectId,minutes,date:d.date||today(),createdAt:Date.now()};db.timeEntries.push(r);write(db);return json(res,200,r)}
 if(p==='/api/timer/cancel'&&req.method==='POST'){let db=read(),user=auth(req,res,db);db.timers=db.timers.filter(x=>x.userId!==user.id);write(db);return json(res,200,{ok:true})}
 if(p==='/api/time'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let from=u.searchParams.get('from')||today(),to=u.searchParams.get('to')||today(),items=db.timeEntries.filter(x=>x.userId===user.id&&x.date>=from&&x.date<=to);return json(res,200,{items,total:items.reduce((n,x)=>n+x.minutes,0)})}if(req.method==='POST'){let d=await body(req);if(!d.title||!Number(d.minutes))return json(res,400,{error:'عنوان و مدت زمان لازم است.'});let r={id:id(),userId:user.id,title:d.title.trim(),projectId:d.projectId||null,minutes:Number(d.minutes),date:d.date||today(),createdAt:Date.now()};db.timeEntries.push(r);write(db);return json(res,201,r)}}
 if(p==='/api/accounts'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let accounts=db.accounts.filter(x=>x.userId===user.id),balances={};db.transactions.filter(x=>x.userId===user.id).forEach(x=>{let a=x.account||'بدون حساب';balances[a]=(balances[a]||0)+(x.kind==='income'?x.amount:-x.amount)});return json(res,200,{accounts:accounts.map(x=>({...x,balance:(x.openingBalance||0)+(balances[x.name]||0)}))})}if(req.method==='POST'){let d=await body(req);if(!d.name)return json(res,400,{error:'نام حساب لازم است.'});if(db.accounts.some(x=>x.userId===user.id&&x.name===d.name.trim()))return json(res,409,{error:'حسابی با این نام قبلاً ساخته شده.'});let r={id:id(),userId:user.id,name:d.name.trim(),type:d.type||'card',openingBalance:Number(d.openingBalance||0),createdAt:Date.now()};db.accounts.push(r);write(db);return json(res,201,r)}}
 if(p==='/api/budgets'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let month=u.searchParams.get('month')||today().slice(0,7),budgets=db.budgets.filter(x=>x.userId===user.id&&x.month===month),spent={};db.transactions.filter(x=>x.userId===user.id&&x.date.startsWith(month)&&x.kind!=='income').forEach(x=>spent[x.category]=(spent[x.category]||0)+x.amount);return json(res,200,{budgets:budgets.map(x=>({...x,spent:spent[x.category]||0}))})}if(req.method==='POST'){let d=await body(req);if(!d.category||!Number(d.limit))return json(res,400,{error:'دسته و سقف بودجه لازم است.'});let month=d.month||today().slice(0,7),r=db.budgets.find(x=>x.userId===user.id&&x.month===month&&x.category===d.category);if(r)r.limit=Number(d.limit);else{r={id:id(),userId:user.id,month,category:d.category,limit:Number(d.limit)};db.budgets.push(r)}write(db);return json(res,201,r)}}
 if(p.startsWith('/api/portfolio/')&&(req.method==='PATCH'||req.method==='DELETE')){let db=read(),user=auth(req,res,db);let ix=db.investments.findIndex(x=>x.id===p.split('/').pop()&&x.userId===user.id);if(ix<0)return json(res,404,{error:'دارایی پیدا نشد.'});if(req.method==='DELETE'){db.investments.splice(ix,1);write(db);return json(res,200,{ok:true})}let d=await body(req),r=db.investments[ix];for(const k of ['symbol','type','quantity','buyPrice','currentPrice'])if(d[k]!==undefined)r[k]=['quantity','buyPrice','currentPrice'].includes(k)?Number(d[k]):d[k];write(db);return json(res,200,r)}
 if(p==='/api/portfolio'){let db=read(),user=auth(req,res,db);if(req.method==='GET'){let items=db.investments.filter(x=>x.userId===user.id),total=items.reduce((n,x)=>n+(x.quantity*x.currentPrice),0),cost=items.reduce((n,x)=>n+(x.quantity*x.buyPrice),0);return json(res,200,{items,total,cost,pnl:total-cost})}if(req.method==='POST'){let d=await body(req);if(!d.symbol||!Number(d.quantity)||!Number(d.buyPrice))return json(res,400,{error:'نماد، تعداد و قیمت خرید لازم است.'});let r={id:id(),userId:user.id,symbol:d.symbol.toUpperCase(),type:d.type||'crypto',quantity:Number(d.quantity),buyPrice:Number(d.buyPrice),currentPrice:Number(d.currentPrice||d.buyPrice),createdAt:Date.now()};db.investments.push(r);write(db);return json(res,201,r)}}
 let file=p==='/'?'/index.html':p;file=path.normalize(path.join(ROOT,'public',file));if(!file.startsWith(path.join(ROOT,'public')))return json(res,403,{error:'Forbidden'});fs.readFile(file,(e,data)=>{if(e)return json(res,404,{error:'Not found'});let ext=path.extname(file);res.writeHead(200,{'Content-Type':ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'application/javascript':'text/plain'});res.end(data)});
}catch(e){if(e instanceof AuthError)return;console.error(e);json(res,500,{error:'خطای داخلی سرور'})}}
const server=http.createServer((req,res)=>{dbLock=dbLock.then(()=>handleRequest(req,res),()=>handleRequest(req,res))});
server.listen(PORT,'0.0.0.0',()=>console.log(`LifeOS running on ${PORT}`));
