// Derives an OpenAPI 3 spec for the HawkScan DAST scan from the route checks in cloudflare/worker.js
// (the Worker has no framework that could emit one). Run after adding routes:
//   node scripts/gen-openapi.js      → stackhawk/openapi.json
// It reads `p==='/api/…'` / `p.startsWith('/api/…')…endsWith('/…')` conditions and the `req.method==='…'`
// checks next to them. Paths with an id segment become `/api/x/{id}`. Bodies are a generic JSON object
// with the field names this API commonly uses, so the scanner has inputs to test.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const src = fs.readFileSync(path.join(ROOT, 'cloudflare', 'worker.js'), 'utf8');
const ops = new Map(); // path -> Set(method)
const add = (p, m) => { if (!ops.has(p)) ops.set(p, new Set()); ops.get(p).add(m); };

// Each route check starts an `if(` whose condition runs to the first `{`; methods are read from the
// condition plus the handler's opening (mixed-method routes branch on req.method inside).
const re = /if\s*\(\s*(p(?:===|\.startsWith\(|\.match\()[^{]*)\{/g;
let m;
while ((m = re.exec(src))) {
  const cond = m[1], after = src.slice(m.index, m.index + 900);
  let route = null;
  const exact = cond.match(/p===\s*'(\/api\/[^']+)'/);
  const starts = cond.match(/p\.startsWith\('(\/api\/[^']+)'\)/);
  const ends = cond.match(/p\.endsWith\('(\/[^']+)'\)/);
  if (exact) route = exact[1];
  else if (starts) {
    const base = starts[1].endsWith('/') ? starts[1] : starts[1] + '/';
    route = base + '{id}' + (ends ? ends[1] : '');
  }
  if (!route) continue;
  const inCond = [...cond.matchAll(/req\.method\s*===\s*'([A-Z]+)'/g)].map(x => x[1]);
  const methods = inCond.length ? inCond : [...after.matchAll(/req\.method\s*===\s*'([A-Z]+)'/g)].map(x => x[1]);
  (methods.length ? [...new Set(methods)] : ['GET']).forEach(x => add(route, x));
}

const body = {
  required: false,
  content: { 'application/json': { schema: { type: 'object', additionalProperties: true, properties: {
    title: { type: 'string', example: 'test' }, text: { type: 'string', example: 'test' }, name: { type: 'string', example: 'test' },
    amount: { type: 'number', example: 10000 }, date: { type: 'string', example: '2026-10-06' }, note: { type: 'string', example: 'test' },
    kind: { type: 'string', example: 'expense' }, category: { type: 'string', example: 'خوراک' }, status: { type: 'string', example: 'active' },
  } } } },
};
const paths = {};
for (const [p, ms] of [...ops.entries()].sort(([a], [b]) => a.localeCompare(b))) {
  paths[p] = {};
  for (const meth of [...ms].sort()) {
    const op = { operationId: (meth.toLowerCase() + p.replace(/[^a-zA-Z0-9]+/g, '_')).replace(/_+$/, ''), responses: { 200: { description: 'OK' } } };
    if (p.includes('{id}')) op.parameters = [{ name: 'id', in: 'path', required: true, schema: { type: 'string', example: 'x' } }];
    if (['POST', 'PUT', 'PATCH'].includes(meth)) op.requestBody = body;
    paths[p][meth.toLowerCase()] = op;
  }
}
const spec = { openapi: '3.0.3', info: { title: 'LifeOS (هسته) Worker API', version: '1', description: 'Generated by scripts/gen-openapi.js from cloudflare/worker.js' }, servers: [{ url: '/' }], paths };
const out = path.join(ROOT, 'stackhawk', 'openapi.json');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, JSON.stringify(spec, null, 2) + '\n');
const opCount = Object.values(paths).reduce((a, x) => a + Object.keys(x).length, 0);
console.log(`openapi: ${Object.keys(paths).length} paths, ${opCount} operations -> ${path.relative(ROOT, out)}`);
